apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  labels:
    app: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - name: iot-app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: iot-svc
spec:
  selector:
    app: iot-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-ingress
spec:
  rules:
  - host: iot-app.
    http:
      paths:
        pathType: Prefix
        path: /app
        backend:
          service:
            name: iot-svc
            port:
              number: 8888