
require 'yaml'
current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.memory = vagrant_config['memory']
		vb.cpus = vagrant_config['cpus']
	end
	config.vm.define "lelhlamiS" do |master|
		master.vm.box = "ubuntu/bionic64"
		master.vm.network "private_network", ip: vagrant_config['master_ip']
		master.vm.hostname = "lelhlamiS"
		master.vm.synced_folder "./setup", "/vagrant"
		master.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --advertise-address="192.168.56.110" --node-ip="192.168.56.110"

            kubectl apply -f /vagrant/setup-ingress.yaml
			kubectl apply -f /vagrant/setup-deplyment.yaml
			kubectl apply -f /vagrant/setup-services.yaml

			#  Adding hosts
			echo "192.168.56.110 app1.com" | sudo tee -a "/etc/hosts"
			echo "192.168.56.110 app2.com" | sudo tee -a "/etc/hosts"
			echo "192.168.56.110 app3.com" | sudo tee -a "/etc/hosts"

			cat /etc/hosts
		SHELL
	end
end