require 'yaml'
current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.memory = vagrant_config['memory']
		vb.cpus = vagrant_config['cpus']
	end
	config.vm.define "lelhlamiS" do |master|
		master.vm.box = "generic/debian11"
		master.vm.network "private_network", ip:  vagrant_config['master_ip']
		master.vm.hostname = "lelhlamiS"
		master.vm.synced_folder "./setup", "/vagrant"
		master.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --advertise-address="192.168.56.110" --node-ip="192.168.56.110"
			echo "Waiting for K3s token..."
      
			# Ensure the token file is created
			while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do
				sleep 1
			done

			# Copy the token to a shared config file
			sudo cat "/var/lib/rancher/k3s/server/node-token" > /vagrant/server-token.txt
			echo "K3s token saved in /vagrant/config"
		SHELL
	end
	config.vm.define "lelhlamiSW" do |agent|
		agent.vm.box = "generic/debian11"
		agent.vm.network "private_network", ip: vagrant_config['agent_ip']
		agent.vm.hostname = "lelhlamiSW"
		agent.vm.synced_folder "./setup", "/vagrant"
		agent.vm.provision "shell", inline: <<-SHELL
			SERVER_IP="192.168.56.110"
			echo "K3s token saved to /vagrant/#{vagrant_config['k3s_token']}"
			while [ ! -e "/vagrant/server-token.txt" ]; do
				sleep 1
			done
			TOKEN=$(cat /vagrant/server-token.txt)
			curl -sfL https://get.k3s.io | K3S_URL="https://$SERVER_IP:6443" K3S_TOKEN=$TOKEN sh -s - -i "192.168.56.111"
		SHELL
	end
end