Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	end
	config.vm.define "lelhlamiS" do |s|
		s.vm.box = "generic/debian11"
		s.vm.network "private_network", ip: "192.168.56.110"
		s.vm.hostname = "lelhlamiS"
	end
end