apiVersion: v1
kind: Service
metadata:
  name: webapp3-service
spec:
  selector:
    app: webapp3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
spec:
  selector:
    app: webapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
