apiVersion: apps/v1   
kind: Deployment    
metadata:            
  name: webapp2-deployment    
  labels:        
    app: webapp2   
spec:            
  replicas: 3    
  selector:       
    matchLabels: 
      app: webapp2
  template:        
    metadata:
      labels:    
        app: webapp2
    # spec:        
    #   containers:    
    #   - name: webapp2
    #     image: wilS/webapp2
    #     ports:
    #       - containerPort: 80
    spec:
      containers:
      - name: webapp2
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webapp2-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webapp2-volume
        hostPath:
          path: /vagrant/rsc/app2
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
spec:
  selector:
    app: webapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80