apiVersion: apps/v1   
kind: Deployment    
metadata:            
  name: webapp1-deployment    
  labels:        
    app: webapp1   
spec:            
  replicas: 1    
  selector:       
    matchLabels: 
      app: webapp1
  template:        
    metadata:
      labels:    
        app: webapp1
    # spec:        
    #   containers:    
    #   - name: webapp1
    #     image: vitejs
    #     ports:
    #       - containerPort: 80
    spec:
      containers:
      - name: webapp1
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webapp1-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webapp1-volume
        hostPath:
          path: /vagrant/rsc/app1
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
spec:
  selector:
    app: webapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80